### PR TITLE
Owned

### PR DESCRIPTION
**Pull request by nerdrew**
Alternative to https://github.com/tafia/quick-protobuf/pull/139.

The rental crate is in bugfix only mode: https://github.com/jpernst/rental/issues/34.

Instead of using the rental crate, it looks like the same thing can be done using [Pin](https://doc.rust-lang.org/std/pin/index.html)

### CODE REVIEW

**Comment by tafia** [comment]
Thanks!
I'm not super familiar with pin api yet. I may need some time to digest what you've done. Let me 2-3 days :)

**Comment by nerdrew** [comment]
No hurry. I'll keep working on my app using it and see if I have any issues.

**Comment by nerdrew** [comment]
Friendly PR bump ;p

**Comment by tafia** [comment]
Thanks again!

**Comment by nerdrew** [comment]
No, thank you for the awesome proto library :)

**Pull request merged**
