### PR TITLE
Add prost benchmarks

### PR DESCRIPTION
**Pull request by overvenus**
Hello,

There is a new protobuf crate [Prost]. I think it would be a good idea to benchmark it too. :-)

This PR does:
 1. update rust-protobuf.
 2. update generated files by latest rust-protobuf and quick-protobuf
 3. add prost benchmarks.

TBD:
 - [x] https://github.com/danburkert/prost/issues/17
 - [x] dead_code warning in perftest_data_prost.rs danburkert/prost#19
 - [x] updating benchmark result.
 - [x] update perftest_data_quick.rs #59 

[Prost]: https://github.com/danburkert/prost

### CODE REVIEW

**Comment by tafia** [comment]
Awesome
Thanks!

**Comment by tafia** [comment]
I just merged #59, about codegen improvement. There should be no difference performance wise but still the codegen may be different.
Do you mind rebasing your PR in case?
Thanks

**Comment by overvenus** [comment]
@tafia No problem! This PR is WIP, when I think it's ready, I will rebase and squash into one commit. :grinning:

**Comment by overvenus** [comment]
Hello @tafia I think its ready, could you have a look?

**Comment by tafia** [comment]
I'll have a look this week. I don't have time for the moment. Thanks a lot!

**Pull request merged**
