### PR TITLE
rm generated files

### PR DESCRIPTION
**Pull request by nerdrew**

### CODE REVIEW

**Comment by mullr** [comment]
It looks like a few generated files are still committed; is that intentional?

**Comment by nerdrew** [comment]
Ya, @tafia asked to keep a few generated files so we can see what changes when the code gen changes (makes sense to me). I figured keeping the examples around would be helpful.

**Comment by mullr** [comment]
Ah ok, cool. Looks good to me then.

**Comment by tafia** [comment]
Thanks!!

**Pull request merged**
